config/routes.rb
Rails.application.routes.draw do
  get 'mypage/index'
  devise_for :users
  root 'posts#index'
  get '/posts/hashtag/:name', to:'posts#hashtags'
  get '/posts/user/:id', to:'posts#user'
  
  resources :posts, except: [:show] do
      post "/like", to: "likes#like_toggle"
      resources :comments, only: [:create, :destroy]
  end
  resources :follows, only: [:create, :destroy]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
    has_many :comments
    has_and_belongs_to_many :tags
    
    mount_uploader :image, PostImageUploader
    
    after_create do
        post = Post.find_by(id: self.id)
        hashtags = self.content.scan(/#\w+/)
        hashtags.uniq.map do |hashtag|
            tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
            post.tags << tag
        end
    end
    
    before_update do
        post = Post.find_by(id: self.id)
        post.tags.clear
        hashtags = self.content.scan(/#\w+/)
        hashtags.uniq.map do |hashtag|
            tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
            post.tags << tag
        end
    end
    
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments
  has_many :follower_relations, foreign_key: "followed_id", class_name: "Follow"
  has_many :followers, through: :follower_relations, source: :follower
  has_many :following_relation, foreign_key: "follower_id", class_name: "Follow"
  has_many :followings, through: :following_relation, source: :followed
  mount_uploader :avatar, AvatarUploader
  
  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_ownership!, only: [:destroy]
    
    def create
        new_comment = Comment.new(content: params[:content],
                                    post_id: params[:post_id],
                                    user_id: current_user.id)
        new_comment.save 
        redirect_to '/'
    end
    
    def destroy
        @comment.destroy
        redirect_to '/'
    end
    
    private
        def check_ownership!
            @comment = Comment.find_by(id: params[:id])
            redirect_to root_path if @comment.user.id != current_user.id
        end
    
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    before_action :authenticate_user!
    
    def create
        Follow.create(followed_id: params[:followed_id],
                      follower_id: current_user.id)
        redirect_to '/'
    end
    
    def destroy
        Follow.find_by(followed_id: params[:id], 
                       follower_id: current_user.id).destroy
        redirect_to '/'
    end
    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    
    def like_toggle
        like = Like.find_by(user_id: current_user.id,
                            post_id: params[:post_id])
        if like.nil?
            Like.create(user_id: current_user.id,
                        post_id: params[:post_id])
        else
            like.destroy
        end
        
        redirect_to '/'
    end
    
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
    @posts = Post.all.order('created_at desc')
    @posts_count = current_user.posts.length
    @user_id = current_user.id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_ownership, only: [:edit, :update, :destroy]
  
  def index
    @posts = Post.all.order('created_at desc')
    @posts_count = current_user.posts.length
  end
  
  def new
  end
  
  def create
    new_post = Post.new(user_id: current_user.id,
                        content: params[:content],
                        image: params[:image])
    if new_post.save
      redirect_to root_path
    else
      redirect_to new_post_path
    end
  end
  
  def edit
  end
  
  def update
    @post.content = params[:content]
    @post.image = params[:image]
    
    if @post.save
      redirect_to root_path
    else
      render :edit
    end
  end
  
  def destroy
    @post.destroy
    redirect_to root_path
  end
  
  def hashtags
    tag = Tag.find_by(name: params[:name])
    @posts = tag.posts
    @posts_count = current_user.posts.length
  end
  
  def user
    # @post = Post.find_by(user_id: params[:id])
    @user_id = params[:id]
    @posts = Post.all.order('created_at desc')
    @posts_count = current_user.posts.length
  end
  
  def check_ownership
    @post = Post.find_by(id: params[:id])
    redirect_to root_path if @post.user_id != current_user.id
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def render_with_hashtags(body)
       body.gsub(/#\w+/){|word| link_to word, "/posts/hashtag/#{word.delete('#')}"}.html_safe 
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imstagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <div class="sticky">
          <a href="/" class="brand-logo">Imstagram</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down"> 
            <% if user_signed_in? %>
              <li>환영합니다, <strong><%= current_user.name %></strong>님</li>
              <!--<li><a href="/mypage/index">My Page</a></li>-->
              <li><%= link_to 'My Page', "/posts/user/#{current_user.id}" %></li>
              <li><%= link_to '개인정보수정', edit_user_registration_path %></li>
              <li><%= link_to '로그아웃', destroy_user_session_path, method: 'delete' %></li>
            <% else %>
              <li><a href="/users/sign_in">로그인</a></li>
              <li><a href="/users/sign_up">회원가입</a></li>
            <% end %>
          </ul>
        </div>
      </div>  
    </nav>
    <%= yield %>
  </body>
</html>

app/views/mypage/_post.html.erb
<div class="card-panel">
    <div class="card-content">
        <% if post.user.avatar %>
            <img class="circle thumbnail" src="<%= post.user.avatar.thumb.url %>">
        <% end %>
        <span class="card-title"><%= post.user.name %></span>
        <span class="right"><%= post.created_at %></span>
        <div class="content">
            <div class="card-image">
                <% if post.image.url %>
                    <img src="<%= post.image.url %>">
                <% end %>
            </div>
            <p class="pre-line"><%= render_with_hashtags(post.content) %></p>
            <% if current_user.is_like?(post) %>
                <%= form_tag post_like_path(post), method: "post", class: "inline left" do %>
                    <button class="btn-small blue-text text-darken-4 blue lighten-4 waves-effect waves-light" type="submit" name="action">좋아요
                        <i class="material-icons left">thumb_up</i>
                    </button>
                <% end %>
            <% else %>
                <%= form_tag post_like_path(post), method: "post", class: "inline left" do %>
                    <button class="btn-small black-text grey lighten-2 waves-effect waves-light" type="submit" name="action">좋아요
                        <i class="material-icons left">thumb_up</i>
                    </button>
                <% end %>
            <% end %>            
            <% if user_signed_in? && current_user != post.user %>
                <% if current_user.followings.include?(post.user) %>
                    <%= form_tag follow_path(post.user.id), method: "delete", class: "right" do %>
                        <button class="btn-small red-text text-darken-4 red lighten-4 waves-effect waves-light">팔로우
                            <i class="material-icons left">favorite</i>
                        </button>
                    <% end %>
                <% else %>
                    <%= form_tag follows_path, method: :post, class: "right" do %>
                        <input type="hidden", name="followed_id" value="<%= post.user.id %>">
                        <button class="btn-small black-text grey lighten-2 waves-effect waves-light">팔로우
                            <i class="material-icons left">favorite_border</i>
                        </button>
                    <% end %>
                <% end %>
            <% end %>
            <% if user_signed_in? && current_user.id == post.user_id %>
                    <%= form_tag post_path(post), method: "delete", class: "right" do %>
                        <button class="btn-small black-text grey lighten-2 waves-effect waves-light">삭제</button>
                    <% end %>
                    <%= form_tag edit_post_path(post), method: "get", class: "right" do %>
                        <button class="btn-small black-text grey lighten-2 waves-effect waves-light">수정</button>
                    <% end %>                    
            <% end %>
        </div>
    </div>
                
    <div class="card-action">
        <br><br>
        <%= post.likes.size %> 명이 좋아합니다.
        <%= form_tag post_comments_path(post) do %>
            <div class="input-field">
                <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "댓글을 작성해 주세요", required: true %>
            </div>
            <div class="input-field">
                <%= button_tag "댓글 쓰기", class: "btn red lighten-1" %>
            </div>
        <% end %>
        <% if post.comments.present? %>
            <ul class="collection">
                <% post.comments.each do |comment| %>
                    <li class="collection-item">
                        <% if comment.user.avatar %>
                            <img class="circle thumbnail" src="<%= comment.user.avatar.thumb.url %>">
                        <% end %>
                        <span class="title"><%= comment.user.name %></span>
                        <span class="right"><%= comment.created_at %></span>
                        <p class="pre-line"><%= comment.content %></p>
                        <% if comment.user.id == current_user.id %>
                            <div><%= link_to "삭제", post_comment_path(post, comment), method: "delete" %></div>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        <% end %>
    </div>
</div>

app/views/mypage/index.html.erb
<div class="container">
    <div class="row">
        <div class="col s12 m9">
            <% @posts.each do |post| %>
                <% if @user_id == post.user_id %>
                    <%= render partial: 'post', object: post %>
                <% end %>
            <% end %>
        </div>
        <div class="col s12 m3">
            <div class="card sticky-sidebar">
                <div class="card-image">
                    <img src="<%= current_user.avatar.url %>" />
                </div>
                <div class="card-content">
                    <div class="card-title"><%= current_user.name %></div>
                    <p>이메일 : <%= current_user.email %></p>
                    <p>올린 글 개수 : <%= @posts_count %></p>
                    <p>팔로워 : <%= current_user.followers.length %></p>
                    <p>팔로잉 : <%= current_user.followings.length %></p>
                    
                    <%= link_to new_post_path do %>
                        <button class="btn red lighten-1">글 쓰기</button>
                    <% end %>
                </div>
            </div>
        </div>        
    </div>
</div>

app/views/posts/_post.html.erb
<div class="card post">
    <div class="card-content">
        <% if post.user.avatar %>
            <img class="circle thumbnail" src="<%= post.user.avatar.thumb.url %>">
        <% end %>
        <span class="card-title"><%= post.user.name %></span>
        <span><%= post.created_at %></span>
        <div class="content">
            <% if user_signed_in? && current_user != post.user %>
                <% if current_user.followings.include?(post.user) %>
                    <%= form_tag follow_path(post.user.id), method: "delete", class: "right" do %>
                        <button class="btn">팔로우 취소</button>
                    <% end %>
                <% else %>
                    <%= form_tag follows_path, method: :post, class: "right" do %>
                        <input type="hidden", name="followed_id" value="<%= post.user.id %>">
                        <button class="btn">팔로우</button>
                    <% end %>
                <% end %>
            <% end %>
            <div class="card-image">
                <% if post.image.url %>
                    <img src="<%= post.image.url %>">
                <% end %>
            </div>
            <p class="pre-line"><%= post.content %></p>
        </div>
    </div>
                
    <div class="card-action">
        <%= post.likes.size %> 명이 좋아합니다.
        <% if current_user.is_like?(post) %>
            <%= link_to "좋아요 취소", post_like_path(post), method: "post" %>
        <% else %>
            <%= link_to "좋아요", post_like_path(post), method: "post" %>
        <% end %>
        <% if current_user.id == post.user_id %>
            <%= link_to "삭제", post_path(post), method: "delete", class: "right" %>
            <%= link_to "수정", edit_post_path(post), class: "right" %>
        <% end %>
        <%= form_tag post_comments_path(post) do %>
            <div class="input-field">
                <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "댓글을 작성해 주세요", required: true %>
            </div>
            <div class="input-field">
                <%= button_tag "댓글 쓰기", class: "btn" %>
            </div>
        <% end %>
        <% if post.comments.present? %>
            <ul class="collection">
                <% post.comments.each do |comment| %>
                    <li class="collection-item">
                        <span class="title"><%= comment.user.name %></span>
                        <span class="right"><%= comment.created_at %></span>
                        <p class="pre-line"><%= comment.content %></p>
                        <% if comment.user.id == current_user.id %>
                            <div><%= link_to "삭제", post_comment_path(post, comment), method: "delete" %></div>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        <% end %>
    </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
    <div class="row">
      <div class="card col s12">
        <div class="card-content">
          <div class="card-title">수정하기</div>
              <%= form_tag post_path(@post), method: "patch", multipart: true do %>
                  <input type="hidden" name="id" value="<%= @post.id %>">
                  <div class="input-field">
                    <%= file_field_tag :image %>
                  </div>
                  
                  <div class="input-field">
                    <%= text_area_tag :content, @post.content, class: "materialize-textarea", placesholder: "무슨 생각을 하고 있나요?" %>
                  </div>
              
                  <div class="input-field">
                    <%= button_tag "수정하기", class: "btn red lighten-1" %>
                  </div>
              <% end %>
        </div>
      </div>
    </div>
</div>

app/views/posts/hashtags.html.erb
<div class="container">
    <div class="row">
        <div class="col s12 m9">
            <% @posts.each do |post| %>
                <%= render partial: 'post', object: post %>
            <% end %>
        </div>
        <div class="col s12 m3">
            <div class="card sticky-sidebar">
                <div class="card-image">
                    <img src="<%= current_user.avatar.url %>" />
                </div>
                <div class="card-content">
                    <div class="card-title"><%= current_user.name %></div>
                    <p>이메일 : <%= current_user.email %></p>
                    <p>올린 글 개수 : <%= @posts_count %></p>
                    <p>팔로워 : <%= current_user.followers.length %></p>
                    <% current_user.followers.each do |f| %>
                        <%= link_to "/posts/user/#{f.id}" do %>
                            <button class="btn-small black-text teal lighten-4 waves-effect waves-light">
                                <%= f.name %>
                            </button>
                        <% end %>
                    <% end %>
                    <p>팔로잉 : <%= current_user.followings.length %></p>
                    <% current_user.followings.each do |f| %>
                        <%= link_to "/posts/user/#{f.id}" do %>
                            <button class="btn-small black-text cyan lighten-4 waves-effect waves-light">
                                <%= f.name %>
                            </button>
                        <% end %>
                    <% end %>
                    <br><br>
                    <%= link_to new_post_path do %>
                        <button class="btn red lighten-1">글 쓰기</button>
                    <% end %>
                </div>
            </div>
        </div>        
    </div>
</div>

app/views/posts/index.html.erb
<div class="container">
    <div class="row">
        <div class="col s12 m3">
            <div class="card">
                <div class="card-image">
                    <img src="<%= current_user.avatar.url %>" />
                </div>
                <div class="card-content">
                    <div class="card-title"><%= current_user.name %></div>
                    <p>이메일 : <%= current_user.email %></p>
                    <p>올린 글 개수 : <%= @posts_count %></p>
                    <p>팔로워 : <%= current_user.followers.length %></p>
                    <p>팔로잉 : <%= current_user.followings.length %></p>
                    
                    <%= link_to new_post_path do %>
                        <button class="btn">글 쓰기</button>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col s12 m9">
            <% @posts.each do |post| %>
                <%= render partial: "post", object: post %>
            <% end %>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="container">
    <div class="row">
      <div class="card col s12">
        <div class="card-content">
          <div class="card-title">새 글 작성하기</div>
          <%= form_tag posts_path, multipart: true do %>
              <div class="input-field">
                  <%= file_field_tag :image %>
              </div>
              
              <div class="input-field">
                <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "무슨 생각을 하고 있나요?" %>
              </div>
              
              <div class="input-field">
                <%= button_tag "작성하기", class: "btn red lighten-1" %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/posts/user.html.erb
<div class="container">
    <div class="row">
        <div class="col s12 m9">
            <% @posts.each do |post| %>
                <% if @user_id.to_i() == post.user_id %>
                    <%= render partial: 'post', object: post %>
                <% end %>
            <% end %>
        </div>
        <div class="col s12 m3">
            <div class="card sticky-sidebar">
                <div class="card-image">
                    <img src="<%= current_user.avatar.url %>" />
                </div>
                <div class="card-content">
                    <div class="card-title"><%= current_user.name %></div>
                    <p>이메일 : <%= current_user.email %></p>
                    <p>올린 글 개수 : <%= @posts_count %></p>
                    <p>팔로워 : <%= current_user.followers.length %></p>
                    <% current_user.followers.each do |f| %>
                        <%= link_to "/posts/user/#{f.id}" do %>
                            <button class="btn-small black-text teal lighten-4 waves-effect waves-light">
                                <%= f.name %>
                            </button>
                        <% end %>
                    <% end %>
                    <p>팔로잉 : <%= current_user.followings.length %></p>
                    <% current_user.followings.each do |f| %>
                        <%= link_to "/posts/user/#{f.id}" do %>
                            <button class="btn-small black-text cyan lighten-4 waves-effect waves-light">
                                <%= f.name %>
                            </button>
                        <% end %>
                    <% end %>
                    <br><br>
                    <%= link_to new_post_path do %>
                        <button class="btn red lighten-1">글 쓰기</button>
                    <% end %>
                </div>
            </div>
        </div>        
    </div>
</div>